In [3]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [4]:
engine = create_engine(
    "mysql+pymysql://root:Yesubabu%408309@localhost/consumer360"
)

In [5]:
query = """
SELECT *
FROM retail_sales_clean
"""

In [6]:
df = pd.read_sql(query, engine)

In [7]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,SalesAmount
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom\r,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom\r,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom\r,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom\r,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom\r,20.34

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397884 entries, 0 to 397883
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    397884 non-null  object
 1   StockCode    397884 non-null  object
 2   Description  397884 non-null  object
 3   Quantity     397884 non-null  int64
 4   InvoiceDate  397884 non-null  datetime64[ns]
 5   UnitPrice    397884 non-null  float64
 6   CustomerID   397884 non-null  int64
 7   Country      397884 non-null  object
 8   SalesAmount  397884 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(4)
memory usage: 27.3+ MB

In [9]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397884 entries, 0 to 397883
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    397884 non-null  object
 1   StockCode    397884 non-null  object
 2   Description  397884 non-null  object
 3   Quantity     397884 non-null  int64
 4   InvoiceDate  397884 non-null  datetime64[ns]
 5   UnitPrice    397884 non-null  float64
 6   CustomerID   397884 non-null  int64
 7   Country      397884 non-null  object
 8   SalesAmount  397884 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(4)
memory usage: 27.3+ MB

In [30]:
snapshot_date = df["InvoiceDate"].max() + pd.Timedelta(days=1)

In [31]:
print(snapshot_date)

2011-12-10 12:50:00

In [32]:
rfm = df.groupby("CustomerID").agg({

    "InvoiceDate": lambda x: (snapshot_date - x.max()).days,

    "InvoiceNo": "nunique",

    "SalesAmount": "sum"

})

In [33]:
rfm.columns = ["Recency","Frequency","Monetary"]

In [34]:
rfm.head()

            Recency  Frequency  Monetary
CustomerID
12346           326          1  77183.60
12347             2          7   4310.00
12348            75          4   1797.24
12349            19          1   1757.55
12350           310          1    334.40

In [35]:
rfm.describe()

           Recency    Frequency       Monetary
count  4338.000000  4338.000000    4338.000000
mean     92.536422     4.272015    2054.266460
std     100.014169     7.697998    8989.230441
min       1.000000     1.000000       3.750000
25%      18.000000     1.000000     307.415000
50%      51.000000     2.000000     674.485000
75%     142.000000     5.000000    1661.740000
max     374.000000   209.000000  280206.020000

In [36]:
rfm["R_Score"] = pd.qcut(
    rfm["Recency"],
    5,
    labels=[5,4,3,2,1]
)

In [37]:
rfm.head()

            Recency  Frequency  Monetary R_Score
CustomerID
12346           326          1  77183.60       1
12347             2          7   4310.00       5
12348            75          4   1797.24       2
12349            19          1   1757.55       4
12350           310          1    334.40       1

In [38]:
rfm["F_Score"] = pd.qcut(
    rfm["Frequency"].rank(method="first"),
    5,
    labels=[1,2,3,4,5]
)

In [39]:
rfm.head()

            Recency  Frequency  Monetary R_Score F_Score
CustomerID
12346           326          1  77183.60       1       1
12347             2          7   4310.00       5       5
12348            75          4   1797.24       2       4
12349            19          1   1757.55       4       1
12350           310          1    334.40       1       1

In [40]:
rfm["M_Score"] = pd.qcut(
    rfm["Monetary"],
    5,
    labels=[1,2,3,4,5]
)

In [41]:
rfm.head()

            Recency  Frequency  Monetary R_Score F_Score M_Score
CustomerID
12346           326          1  77183.60       1       1       5
12347             2          7   4310.00       5       5       5
12348            75          4   1797.24       2       4       4
12349            19          1   1757.55       4       1       4
12350           310          1    334.40       1       1       2

In [28]:
rfm = rfm.drop(columns=['M_Score'])

In [42]:
rfm["R_Score"] = rfm["R_Score"].astype(int)

In [43]:
rfm.head()

            Recency  Frequency  Monetary  R_Score F_Score M_Score
CustomerID
12346           326          1  77183.60        1       1       5
12347             2          7   4310.00        5       5       5
12348            75          4   1797.24        2       4       4
12349            19          1   1757.55        4       1       4
12350           310          1    334.40        1       1       2

In [44]:
rfm["F_Score"] = rfm["F_Score"].astype(int)

In [45]:
rfm.head()

            Recency  Frequency  Monetary  R_Score  F_Score M_Score
CustomerID
12346           326          1  77183.60        1        1       5
12347             2          7   4310.00        5        5       5
12348            75          4   1797.24        2        4       4
12349            19          1   1757.55        4        1       4
12350           310          1    334.40        1        1       2

In [ ]:
rfm["M_Score"] = rfm["M_Score"].astype(int)

In [47]:
rfm["RFM_Score"] = (
    rfm["R_Score"].astype(str) +
    rfm["F_Score"].astype(str) +
    rfm["M_Score"].astype(str)
)

In [48]:
print("RFM_SCORE SUCCESSFULLY COMPLETED")

RFM_SCORE SUCCESSFULLY COMPLETED

In [49]:
rfm.head()

            Recency  Frequency  Monetary  R_Score  F_Score M_Score RFM_Score
CustomerID
12346           326          1  77183.60        1        1       5       115
12347             2          7   4310.00        5        5       5       555
12348            75          4   1797.24        2        4       4       244
12349            19          1   1757.55        4        1       4       414
12350           310          1    334.40        1        1       2       112

In [50]:
def segment_customer(row):

    if row["R_Score"] >=4 and row["F_Score"] >=4 and row["M_Score"] >=4:
        return "Champion"

    elif row["R_Score"] >=3 and row["F_Score"] >=3:
        return "Loyal Customer"

    elif row["R_Score"] >=4:
        return "Potential Loyalist"

    elif row["R_Score"] <=2 and row["F_Score"] >=3:
        return "At Risk"

    elif row["R_Score"] ==1 and row["F_Score"] ==1:
        return "Churn Risk"

    else:
        return "Others"

In [52]:
rfm["Segment"] = rfm.apply(segment_customer, axis=1)

In [55]:
rfm.head(10)

,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score,Segment
CustomerID,,,,,,,,
12346,326,1,77183.60,1,1,5,115,Churn Risk
12347,2,7,4310.00,5,5,5,555,Champion
12348,75,4,1797.24,2,4,4,244,At Risk
12349,19,1,1757.55,4,1,4,414,Potential Loyalist
12350,310,1,334.40,1,1,2,112,Churn Risk
12352,36,8,2506.04,3,5,5,355,Loyal Customer
12353,204,1,89.00,1,1,1,111,Churn Risk
12354,232,1,1079.40,1,1,4,114,Churn Risk
12355,214,1,459.40,1,1,2,112,Churn Risk
12356,23,3,2811.43,4,3,5,435,Loyal Customer

In [56]:
rfm["Segment"].value_counts()

Segment
Others                1052
Loyal Customer         998
Champion               962
At Risk                643
Churn Risk             364
Potential Loyalist     319
Name: count, dtype: int64

In [57]:
rfm.groupby("Segment")[

    ["Recency","Frequency","Monetary"]

].mean().round(2)

                    Recency  Frequency  Monetary
Segment
At Risk              152.84       3.40   1244.99
Champion              12.86      11.08   6038.82
Churn Risk           278.68       1.00    544.05
Loyal Customer        34.09       3.71   1477.08
Others               142.02       1.16    459.32
Potential Loyalist    18.52       1.24    458.20

In [61]:
rfm.to_csv(
    r"C:\Projects\Consumer360\01_Data\04_Output\RFM_Customers.csv",
    index=False,
    encoding="utf-8"
)

In [62]:
rfm.to_sql(
    "customer_rfm",
    engine,
    if_exists="replace",
    index=True
)

4338

In [63]:
rfm.head()

,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score,Segment
CustomerID,,,,,,,,
12346,326,1,77183.60,1,1,5,115,Churn Risk
12347,2,7,4310.00,5,5,5,555,Champion
12348,75,4,1797.24,2,4,4,244,At Risk
12349,19,1,1757.55,4,1,4,414,Potential Loyalist
12350,310,1,334.40,1,1,2,112,Churn Risk

In [64]:
rfm["Segment"].value_counts()

Segment
Others                1052
Loyal Customer         998
Champion               962
At Risk                643
Churn Risk             364
Potential Loyalist     319
Name: count, dtype: int64

In [65]:
rfm.groupby("Segment")[["Recency", "Frequency", "Monetary"]].mean()

                       Recency  Frequency     Monetary
Segment
At Risk             152.844479   3.404355  1244.994636
Champion             12.861746  11.080042  6038.816081
Churn Risk          278.684066   1.000000   544.054038
Loyal Customer       34.091182   3.714429  1477.081714
Others              142.015209   1.156844   459.320810
Potential Loyalist   18.517241   1.241379   458.202414